### ISSUE TITLE
await None

### ISSUE THREAD

**Issue by fcollonval** [ideonate/jhsingle-native-proxy#4]
Hey thanks for the great tool.

Using cdsdashboard, I got the following error when starting a dashboard:

```
[I 2020-06-26 09:57:43.527 JupyterHub proxy:262] Adding user fcollonval to proxy /user/fcollonval/dash-sin-and-cos-graph/ => http://127.0.0.1:42893
ERROR:tornado.application:Uncaught exception GET /user/fcollonval/dash-sin-and-cos-graph/ (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:42893', method='GET', uri='/user/fcollonval/dash-sin-and-cos-graph/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/opt/conda/lib/python3.7/site-packages/jhsingle_native_proxy/websocket.py", line 94, in get
    return await self.http_get(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 592, in http_get
    return await self.proxy(self.port, path)
  File "/opt/conda/lib/python3.7/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 586, in proxy
    return await self.oauth_proxy(port, path)
TypeError: object NoneType can't be used in 'await' expression
```

Installation:

In Docker with base docker = `debian:buster-slim`

Python package of interest:
```
python 3.7.0
cdsdashboards          0.0.19             
jhsingle-native-proxy  0.3.1              
jupyter-archive        0.6.2              
jupyter-client         6.1.3              
jupyter-core           4.6.3              
jupyter-server         0.1.1              
jupyter-telemetry      0.0.5              
jupyterhub             1.1.0              
jupyterlab             2.1.5              
jupyterlab-git         0.20.0             
jupyterlab-pygments    0.1.1              
jupyterlab-server      1.1.5
```

**Comment by danlester** [comment]
Thanks for the report, but actually this is expected behavior!

It is due to a necessary workaround in some of the core JupyterHub code [here](https://github.com/jupyterhub/jupyterhub/blob/76c9111d80660e93578f80dbe441cfb702c1b207/jupyterhub/services/auth.py#L903
).

I have some plans to make this redundant though, and in the meantime, I will document it to avoid worrying users.

However, of course this error message should just show up in the logs but not impede the Dashboard. Please could I ask, in your case is there ultimately a problem with the dashboard? (Or did you just notice the error in the logs and it caused concern even though there were no apparent side effects?)

**Comment by fcollonval** [comment]
Thanks for the reply @danlester 

> However, of course this error message should just show up in the logs but not impede the Dashboard. Please could I ask, in your case is there ultimately a problem with the dashboard? (Or did you just notice the error in the logs and it caused concern even though there were no apparent side effects?)

Indeed there was at the end no problem to display the dashboard. I saw it looking at the logs.

> I remember seeing [maybe_future](https://www.tornadoweb.org/en/stable/gen.html?highlight=ensure_future#tornado.gen.maybe_future) in some jupyter packages. But I don't know if it is appropriate here - and I'm unsure it is compatible with `asyncio`.

**Comment by danlester** [comment]
From memory I think maybe_future will turn non-asyncio futures (e.g. [concurrent.futures.Future](concurrent.futures.Future)) into an asyncio future.

Actually the problem isn't as complicated as it sounds - it's really just down to the limitations of the way authentication is built into Tornado, and this is a workaround by the Jupyter team. But it just feels a shame to rewrite some of the Tornado auth just in order to avoid these logs... But I think it will come out as a side effect of other features in the future anyway.
